### ISSUE TITLE
Getting Yak list failed

### ISSUE THREAD

**Issue by XiziR** [akashlevy/Yaklient#1]
First of all, thanks for the comprehensive package and nice documentation. I was trying to run your example code, but after this line: 

> > > user = User(exeter, "21C6CA60E3AA43C4B8C18B943394E111")
> > > , I get the following error:
> > > raise ParsingResponseError("Getting Yak list failed", raw_data)
> > > ParsingResponseError: Getting Yak list failed
> > > Response:
> > > Do you know what causes that? I tried different UserIDs too. But, it didn't help.

Thanks.

**Comment by akashlevy** [comment]
Sorry, there were some errors with the new version of YikYak. Problem should be fixed now.

**Comment by XiziR** [comment]
Unfortunately, I still face the same problem.

**Comment by akashlevy** [comment]
Yeah, actually it's happening for me too, now... will try to fix this when I get a chance

**Comment by akashlevy** [comment]
Hi XiziR,

Sorry for replying so late, not sure if you're still interested. I just fixed the issue. You need to keep randomizing the user agent in order for it to work. I have enable user agent randomization and Yaklient seems to be working for me. Let me know if it is working for you now. :)

**Comment by XiziR** [comment]
Sorry for replying this late. I missed the notification of your comment. I have to install the package again and give it a try. Anyways, thanks for your time and support.
