### ISSUE TITLE
Error:  No JSON object could be decoded

### ISSUE THREAD

**Issue by naaly17** [akashlevy/Yaklient#6]
First try using this library, tried with several different user id's, get this error "No JSON object could be decoded"
when setting: user=user(school name, id)

**Comment by akashlevy** [comment]
Hi naaly17,

I have heard from several people that this library is not working right now. I am going to take another look at trying to fix it during my Thanksgiving break.

**Comment by ehusarci** [comment]
Hi @akashlevy,

I hope you had a great Thanksgiving break! I'm curious if you have made any progress on this. Is this due to a YikYak API update or just a change in YIKYAK_APIKEY / PARSE_CLIENTKEY?

**Comment by dpeters1** [comment]
Interested in hearing about progress as well. AFAIK there aren't any working python libraries, terminal programs, etc. that can interact with the yikyak API. Looks like creating a word cloud of post content could be harder than I thought.

**Comment by akashlevy** [comment]
Hi all,

Sorry for replying so late, not sure if you're still interested. I just fixed the issue. You need to keep randomizing the user agent in order for it to work. I have enable user agent randomization and Yaklient seems to be working for me. Let me know if it is working for you now. :)
